# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2022-11-23 20:42
from __future__ import unicode_literals

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Subscriber',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=64, verbose_name='\u0418\u043c\u044f')),
                ('last_name', models.CharField(max_length=64, verbose_name='\u0424\u0430\u043c\u0438\u043b\u0438\u044f')),
                ('email', models.CharField(max_length=128, verbose_name='Email')),
                ('birthday', models.CharField(max_length=10, verbose_name='\u0414\u0430\u0442\u0430 \u0440\u043e\u0436\u0434\u0435\u043d\u0438\u044f')),
                ('group', models.CharField(max_length=32, verbose_name='\u0413\u0440\u0443\u043f\u043f\u0430')),
            ],
        ),
    ]
