# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2022-11-23 20:42
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('subscriber', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MailingList',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=32, verbose_name='\u041d\u0430\u0437\u0432\u0430\u043d\u0438\u0435 \u0440\u0430\u0441\u0441\u044b\u043b\u043a\u0438')),
                ('date_of_completion', models.DateTimeField(default=datetime.datetime(2022, 11, 23, 20, 42, 48, 673157, tzinfo=utc), verbose_name='\u0414\u0430\u0442\u0430 \u0440\u0430\u0441\u0441\u044b\u043b\u043a\u0438')),
            ],
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sent', models.BooleanField(default=False, verbose_name='\u041f\u0438\u0441\u044c\u043c\u043e \u043e\u0442\u043f\u0440\u0430\u0432\u043b\u0435\u043d\u043e')),
                ('open', models.DateTimeField(default=None, verbose_name='\u041a\u043e\u0433\u0434\u0430 \u043f\u0438\u0441\u044c\u043c\u043e \u043e\u0442\u043a\u0440\u044b\u0442\u043e')),
                ('mailing_list', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sender.MailingList', verbose_name='\u0420\u0430\u0441\u0441\u044b\u043b\u043a\u0430')),
                ('subscriber', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='subscriber.Subscriber', verbose_name='\u041f\u043e\u043b\u0443\u0447\u0430\u0442\u0435\u043b\u044c')),
            ],
        ),
    ]
